# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

# all, none, or list of linter keys
APPLY_FIXES: all

# If you use ENABLE variable, all other languages/formats/tooling-formats will
# be disabled by default
# ENABLE:

# If you use ENABLE_LINTERS variable, all other linters will be disabled by
# default
ENABLE_LINTERS:
  - YAML_PRETTIER
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - KOTLIN_DETEKT
  - DART_DARTANALYZER
  - SWIFT_SWIFTLINT

DISABLE:
  - COPYPASTE # Comment to enable checks of excessive copy-pastes
  - SPELL # Comment to enable checks of spelling mistakes

SHOW_ELAPSED_TIME: true

FILEIO_REPORTER: false
# Uncomment if you want MegaLinter to detect errors but not block CI to pass

KOTLIN_DETEKT_ARGUMENTS: -c android_kmp/config/detekt/detekt.yml
JAVASCRIPT_STANDARD_DISABLE_ERRORS: true