name: "Java setup"
description: "Setup Java"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: "21"
        distribution: "temurin"
        cache: gradle